[tool.poetry]
name = "openpy-fxts"
version = "0.2.3"
description = "Various functions and classes for time series forecasting with Machine and Deep Learning"
authors = ["Jorge Lara <jlara@iee.unsj.edu.ar>"]
license = "LICENSE.md"
readme = "README.md"

packages = [{include = "openpy_fxts"}]
exclude = [
    "openpy_fxts/architectures/fxts/hybrids/mdl_vae_exp/*",
    "openpy_fxts/datasets/*"
]

[tool.poetry.dependencies]
python = "^3.10"
build = "1.0.3"
cachecontrol = "0.13.1"
certifi = "2023.11.17"
charset-normalizer = "3.3.2"
cleo = "2.1.0"
colorama = "0.4.6"
contourpy = "1.2.0"
crashtest = "0.4.1"
cycler = "0.12.1"
distlib = "0.3.8"
docutils = "0.20.1"
dulwich = "0.21.7"
fastjsonschema = "2.19.1"
filelock = "3.13.1"
fonttools = "4.47.2"
h5py = "3.10.0"
idna = "3.6"
importlib-metadata = "7.0.1"
installer = "0.7.0"
jaraco-classes = "3.3.0"
joblib = "1.3.2"
keyring = "24.3.0"
kiwisolver = "1.4.5"
llvmlite = "0.41.1"
markdown-it-py = "3.0.0"
matplotlib = "3.8.2"
mdurl = "0.1.2"
minisom = "2.3.1"
more-itertools = "10.2.0"
msgpack = "1.0.7"
nh3 = "0.2.15"
numba = "0.58.1"
numpy = "1.26.3"
packaging = "23.2"
pandas = "2.2.0"
patsy = "0.5.6"
pexpect = "4.9.0"
pillow = "10.2.0"
pkginfo = "1.9.6"
platformdirs = "3.11.0"
poetry = "1.7.1"
poetry-core = "1.8.1"
poetry-plugin-export = "1.6.0"
ptyprocess = "0.7.0"
pygments = "2.17.2"
pyparsing = "3.1.1"
pyproject-hooks = "1.0.0"
python-dateutil = "2.8.2"
pytz = "2023.3.post1"
pywin32-ctypes = "0.2.2"
rapidfuzz = "3.6.1"
readme-renderer = "42.0"
requests = "2.31.0"
requests-toolbelt = "1.0.0"
rfc3986 = "2.0.0"
rich = "13.7.0"
scikit-learn = "1.4.0"
scipy = "1.12.0"
seaborn = "0.13.1"
shellingham = "1.5.4"
six = "1.16.0"
statsmodels = "0.14.1"
threadpoolctl = "3.2.0"
tomli = "2.0.1"
tomlkit = "0.12.3"
tqdm = "4.66.1"
trove-classifiers = "2024.1.8"
tslearn = "0.6.3"
twine = "4.0.2"
tzdata = "2023.4"
urllib3 = "2.1.0"
virtualenv = "20.25.0"
yellowbrick = "1.5"
zipp = "3.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
