[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.1.2.4"
name = "graph-nitta"
authors = [{ name = "Kamono Makoto", email = "chengyaye31@gmail.com" }]
description = "graph library wrapping matplotlib"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["pydantic", "matplotlib"]

[project.urls]
Homepage = "https://github.com/nitta-lab-polymer/graph-nitta"
Issues = "https://github.com/nitta-lab-polymer/graph-nitta/issues"
