[build-system]
requires = [
    "setuptools>=48",
    "wheel >= 0.29.0"
]
build-backend = "setuptools.build_meta"

[project]
name = 'coreflow'
dynamic = [
    'version'
]
description = 'Core flow and Special Core Analysis Interpretaion Tool.'
readme = 'README.md'
authors = [
    { name = 'Roman Manasipov', email = 'romantheorphys@gmail.com' },
    { name = 'Bettina Jenei', email = 'jeneibetti@gmail.com' }
]
license = { file = 'LICENSE' }
requires-python = '>=3.8'
dependencies = [
    "pandas",
    "openpyxl",
    "scipy",
    "plotly",
    "bokeh",
    "matplotlib",
    "seaborn",
    "docker",
]

classifiers = [
    'Operating System :: OS Independent',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
]

[project.urls]
"repository" = "https://github.com/rmanasipov/coreflow"

[tool.setuptools.dynamic]
version = { attr = "coreflow.__version__"}