[package]
name = "deterministic_sql"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "deterministic_sql"
crate-type = ["cdylib"]

[dependencies]
sqlparser = {version = "0.40.0", features = ["visitor"]}
pyo3 = { version = "0.20.0", features = ["extension-module"] }
