[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "asteroidsenv"
dependencies=[
    "gymnasium>=0.26.0",
    "pygame>=2.1.0",
    "numpy>=1.19"
]
version = "1.3.0"
description = "The atari classic asteroids as gymnasium environment"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Laurenz Levi Spielmann", email = "laurenz-levi.spielmann@tu-dortmund.de"}
]
license = {file = "LICENSE"}

[tool.setuptools]
packages = ["asteroidsenv", "asteroidsenv.env"]
