[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ops-py-azure-key-vault-report"
description = "Output a Key Vault Secrets report"
license = {file = ""}
version = "3.0.2"
dynamic = ["readme", "dependencies"]

[tool.setuptools.dynamic]
readme = {file = "", content-type = "text/markdown"}
dependencies = {file = [""]}
