[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.1.11"
name = "process-nitta"
authors = [{ name = "Kamono Makoto", email = "chengyaye31@gmail.com" }]
description = "process experimental data"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["pydantic", "pandas", "pybaselines"]

[project.urls]
Homepage = "https://github.com/nitta-lab-polymer/process-nitta"
Issues = "https://github.com/nitta-lab-polymer/process-nitta/issues"
