[tool.poetry]
name = "pplog"
version = "0.1.19"
description = "Pricing Domain Logging and Monitoring Tool"
authors = ["Paolo Andreas Stall Rechia <paolo_andreas.stall_rechia@mail.schwarz>", "Petar Alper <petar.alper@mail.schwarz>"]
maintainers = ["Paolo Andreas Stall Rechia <paolo_andreas.stall_rechia@mail.schwarz>", "Petar Alper <petar.alper@mail.schwarz>"]
readme = "README.md"
repository = "https://dev.azure.com/schwarzit/schwarzit.ai-public/_git/pplog"

[tool.poetry.dependencies]
python = "^3.9"
pyspark = ">=3.3.2"
omegaconf = "^2.3.0"
great-expectations = "^0.18.8"
azure-identity = "^1.15.0"
azure-eventgrid = "^4.16.0"
logstash-formatter = "^0.5.17"
databricks-sdk = "^0.18.0"

[tool.poetry.group.test.dependencies]
pytest = ">=7.4.4"

[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"
tox = "^4.12.1"

[build-system]
requires = ["poetry-core>=1.8.1"]
build-backend = "poetry.core.masonry.api"

[tool.mypy.logstash_formatter]
ignore_missing_imports = true