[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ops-py-azure-key-vault-alert"
description = "Post Key Vault Secrets report to webhook"
license = {file = ""}
version = "2.2.3"
dynamic = ["readme", "dependencies"]

[tool.setuptools.dynamic]
readme = {file = "", content-type = "text/markdown"}
dependencies = {file = ["requirements.txt"]}
