[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-infinity"
version = "0.0.6"
authors = [
  { name="pydevbuzz", email="pydevbuzz@gmail.com" },
]
dynamic = ["dependencies"]
description = "Unofficial Infinity client packages"
readme = "README.md"
requires-python = ">=3.11.0,<3.11.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
"Homepage" = "https://github.com/pydevbuzz/python-infinity"
"Bug Tracker" = "https://github.com/pydevbuzz/python-infinity/issues"