[tool.poetry]
name = "errorcodes"
version = "0.0.1"
description = "Library that provides utilities for defining error codes for your application."
authors = ["Kornelijus Tvarijanaviƒçius <kornelijus@tvaria.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kornelijus/errorcode"
repository = "https://github.com/kornelijus/errorcode"
classifiers = ["Development Status :: 1 - Planning"]


[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
