[project]
name = "S2ClusterGen"
version = "0.0.4"
authors = [
  { name="Ricardo Santos", email="rsantos@singlestore.com" },
]
description = "S2 - Cluster Generation file"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
]
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
S2ClusterGen = "S2ClusterGen.S2ClusterGen:main"
