[project]
name = "g3tables"
version = "0.1.2"
description = "G3 SW Definition, HW and PLC components, and Visualisation tables parser"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  { name = "Konstantin Mykhailov", email = "kmykhailov@elektroline.cz" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
    'gspread',
    'openpyxl',
    'pandas',
    'python-gitlab',
    'unidecode'
]

[options]
package_dir = {"" = "src"}

[project.urls]
"Homepage" = "https://gitlab.elektroline.cz/plc/systemg3-py/SystemG3Tables"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"g3tables.plc_composition_io_table" = ["io_signals.json"]
"g3tables.utils.gdrive" = ["creds.json"]