[tool.poetry]
name = "milanesas"
version = "0.1.32"
description = "A group of tools to do exploratory analysis."
authors = ["Torrez, Milton <torrez.mn@gmail.com>"]
homepage = "https://torrezmn.github.io/EDA_Helper/eda_helper/"
packages = [
{ include = "milanesas" },  # For code in a custom directory named "mypackage"
]
keywords = ["packaging", "data_science", "pandas"]
readme = ["docs/README.md"]
[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pandas = "^1.5.3"
matplotlib = "^3.5"  # More flexible constraint for broader compatibility
numpy = "^1.23.4"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
