[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "valaya"
version = "0.0.10"
authors = [
    {name = "Sakshine", email = "sakshine108@gmail.com"},
]
description = "A secure and customizable cloud storage system built with an open source client."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
valaya = "valaya.valaya_cli:main"

[project.urls]
Repository = "https://github.com/sakshine108/valaya"