[tool.poetry]
name = "dexpo"
version = "0.1.6"
license = "MIT"
description = "Dependency Exposition Boiled Down"
authors = ["Jack Hadaway <jack.hadaway@outlook.com>"]
readme = "README.md"
homepage = "https://github.com/jackboy2fly/dexpo"
repository = "https://github.com/jackboy2fly/dexpo"

[tool.poetry.scripts]
dexpo = "dexpo.main:app"

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.9.0"}
requests = "2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
