[tool.poetry]
name = "jtorch-utils"
version = "0.1.1"
description = "Tools for PyTorch model development and experimentation."
authors = ["Johannes Traa"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.5"
pandas = "^2.0.3"

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"