[tool.poetry]
name = "pq-dataset"
version = "1.4.6"
description = ""
authors = ["Christian Frost"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.0"
pyarrow = "^15.0.0"
bs4 = "^0.0.2"
loguru = "^0.7.2"
lxml = "^5.1.0"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
