[project]
name = "aiogram2252_page"
version = "0.0.3"
authors = [
  { name="llimonix", email="llimonix123@yandex.com" },
]
description = "Inline pagination for aiogram 2.25.2"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/llimonix/aiogram-pagination-inline-2.25.2"
Issues = "https://github.com/llimonix/aiogram-pagination-inline-2.25.2/issues"