
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sk_in_torch"
version = "0.0.3"
authors = [
  { name="Hao Li", email="haolircplanes@gmail.com" },
]
description = "Torch models rewritten in sklearn format"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/HaoLi111/sk_in_torch/"
Issues = "https://github.com/HaoLi111/sk_in_torch/issues"