[tool.poetry]
name = "switchgrid_python_client"
version = "0.1.2"
description = "Python package to access Switchgrid APIs"
authors = ["Thomas Carli <thomas@switchgrid.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.8.5"
requests = "^2.31.0"
pytest-asyncio = "^0.23.4"


[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"
asynctest = "^0.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
