[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "unstract-adapters"
version = "0.0.6"
description = "Unstract Adapters"
authors = [
    { name = "Zipstack Inc.", email = "devsupport@zipstack.com" },
]
dependencies = [
    "llama-index==0.9.28",
    "openai==1.3.9",
    "google-generativeai==0.3.1",
    "fastembed==0.1.3",
    "huggingface==0.0.1",
    "pymilvus==2.3.4",
    "pinecone-client==2.2.4",
    "pgvector==0.2.4",
    "qdrant-client==1.7.0",
    "supabase==2.2.1",
    "weaviate-client==3.25.3",
    "anthropic==0.7.8",
    "replicate==0.22.0",
    "anyscale==0.5.165",
    "mistralai==0.0.8",
]
requires-python = ">=3.9,<3.12"
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
]

[project.license]
text = "MIT"

[tool.pdm.build]
includes = [
    "src",
]
package-dir = "src"
