# ðŸš€ Label Explorer, GPL-3.0 license
# åŸºäºŽ Electron çš„ YOLO æ ‡ç­¾åˆ†æžä¸Žæ•´åˆå·¥å…· (Python CLIç‰ˆ)


[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "label-explorer"
version = "v0.0.1"
requires-python = ">=3.8"
description = "åŸºäºŽ Electron çš„ YOLO æ ‡ç­¾åˆ†æžä¸Žæ•´åˆå·¥å…· (Python CLIç‰ˆ)"
readme = "README.md"
license = { "text" = "GPL-3.0" }
keywords = ["Electron", "YOLO", "labels", "images"]
authors = [
    { name = "æ›¾é€¸å¤« Zeng Yifu"},
    { name = "é‚“ä¹™åŽ Deng Yihua" }
]
maintainers = [
    { name = "æ›¾é€¸å¤« Zeng Yifu" },
    { name = "é‚“ä¹™åŽ Deng Yihua" }
]
dependencies = [
    "opencv-python>=4.9.0.80",
    "click>=8.1.7",
    "rich>=13.7.0",
    "black>=24.1.1",
    "isort>=5.13.2",
    "mdformat>=0.7.17",
]


[project.scripts]
label-explorer = "label_explorer_cli.label_explorer:entrypoint"


[project.urls]
"Bug Reports" = "https://gitee.com/intelligence-vision/label-explorer/issues"
"Funding" = "https://gitee.com/intelligence-vision"
"Source" = "https://gitee.com/intelligence-vision/label-explorer"


[tool.setuptools]
packages = { find = { where = ["."], include = ["label_explorer_cli", "label_explorer_cli.*"]} }
package-data = { "label_explorer_cli" = ["**/*.css"] }

