[tool.poetry]
name = "smartq-llm-app-utils"
version = "0.0.1-1707181386"
description = ""
authors = ["hwacom_sc_rd2 <aiot.hwacom@gmail.com>"]
readme = "README.md"
packages = [{include = "smartq_llm_app_utils"}]

[tool.poetry.dependencies]
python = "^3.10"
myllmutils = "^0.1.5a"
pydantic-settings = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
