[project]
name = "g3hardware"
version = "0.1.1"
description = "G3 PLC Hardware XML configuration generator"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  { name = "Konstantin Mykhailov", email = "kmykhailov@elektroline.cz" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
  "lxml",
  "python-gitlab",
]

[options]
package_dir = {"" = "src"}

[project.urls]
"Homepage" = "https://gitlab.elektroline.cz/plc/systemg3-py/SystemG3Hardware"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
g3hardware = ["settings.json"]
