[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tdmt"
version = "0.1.7"
description = "A brief description of your app."
authors = [{ name = "Your Name", email = "your.email@example.com" }]
license = "MIT"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ['keyword1', 'keyword2']
dependencies = [
    # List your project dependencies here
    # e.g., "requests >= 2.25.1"
]

[project.urls]
Homepage = "http://example.com"
Repository = "http://example.com/repo"
Documentation = "http://example.com/docs"

[project.scripts]
tdmt = "tdmt.tdmt:main"