[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ops-py-generate-pyproject"
description = "Generate needed pyproject files to use with setuptools"
license = {file = ""}
version = "2.1.0"
dynamic = ["readme", "dependencies"]

[tool.setuptools.dynamic]
readme = {file = "", content-type = "text/markdown"}
dependencies = {file = [""]}
