[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bsb-json"
authors = [{name = "Robin De Schepper", email = "robingilbert.deschepper@unipv.it"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]
requires-python = ">=3.8"
dependencies = ["bsb-core>=4.0.0b0,<=4.0.0b9999"]

[project.entry-points."bsb.config.parsers"]
json = "bsb_json.parser"

[project.entry-points."bsb.config.templates"]
json_templates = "bsb_json.templates"

[tool.flit.module]
name = "bsb_json"

[project.optional-dependencies]
test = ["bsb-test>=0.0.0b7,<=0.0.0b9999", "coverage~=7.0"]
dev = [
    "pre-commit~=3.5",
    "black~=23.11",
    "isort~=5.12",
    "bump2version~=1.0"
]

[tool.isort]
profile = "black"