[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/miml"]

[project]
name = "miml-package"
version = "0.0.10"
authors = [
    { name="Damian Martinez", email="damianmartinezavila@gmail.com" },
]
description = "Multi-instance Multi-label learning package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/p82maavd/miml"
"Bug Tracker" = "https://github.com/p82maavd/miml"