[project]
name = "Sedna"
version = "0.0.04"
authors = [
  { name="Rishit Logar", email="logarrishit@gmail.com" },
]
description = "Sedna is a python package for computational mathematics"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]
[build-system]
requires = ["setuptools>=61.0", "pyttsx3"]
build-backend = "setuptools.build_meta"