[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pbshm-channel-toolbox"
version = "0.1"
authors = [
    { name = "Dan Brennan", email = "d.s.brennan@sheffield.ac.uk" }
]
description = "PBSHM Channel Toolbox"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3",
    "Framework :: Flask"
]
requires-python = ">=3.8.10"
dependencies = [
    "pbshm-core >= 1.1.1",
    "bokeh == 3.3.4"
]

[project.urls]
homepage = "https://github.com/dsbrennan/channel-tools"

[tool.setuptools.packages.find]
exclude = ["instance"]