[tool.poetry]
name = "gyver-tests"
version = "2.0.1"
description = ""
authors = ["Gustavo Correa <self.gustavocorrea@gmail.com>"]
readme = "README.md"
packages = [{ include = "gyver/tests" }]

[tool.poetry.dependencies]
python = "^3.9"
gyver = "^4.0.0"
pytest = "^7.4.2"
faker = "^19.10.0"


[tool.poetry.group.http.dependencies]
aiohttp = "^3.9.3"


[tool.poetry.group.lint.dependencies]
black = "^22.12.0"
isort = "^5.12.0"
autoflake = "^2.0.1"
flake8 = "^6.0.0"


[tool.poetry.group.tests.dependencies]
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
